name: node test
on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: node app.js
      - run: git add .
      - run: git commit -m "updating"
      - run: git push origin master
